### PR TITLE
yuzuMainlineGenerator.py: Fix Nintendo Switch Pro controller mapping

### PR DESCRIPTION
**Pull request by drizzt**
This also works with 8bitdo pro 2 in Switch mode (with gyroscope working)

### CODE REVIEW

**Comment by ordovice** [comment]
Additionally, you're literally just reversing exactly what I have allocated in the code much further down (though I like your handling of it a bit better so I might do that instead)

**Comment by drizzt** [comment]
well, I tried 8bitdo pro and original nintendo switch pro controller and without this code the buttons are reversed

**Comment by ordovice** [comment]
And of coure the ultimate pro is also registering as a type 5, but has other issues.  I've got an SN30 Pro (not a Pro 2) that I can hopefully test in this mode.

**Comment by drizzt** [comment]
I don't have other devices that registers as switch pro, but I think they should behave like the original one

**Comment by ordovice** [comment]
Can you confirm this is the Pro 2 you're talking about?  I'll buy it next if so, so I can compare it to the Ultimate for why they're reversed
https://www.amazon.com/Wireless-Bluetooth-Controller-Joysticks-Vibration/dp/B085STR9R3/ref=sr_1_4?crid=21DUD6E94N959

**Comment by drizzt** [comment]
yes, in switch mode (aka with the mode switch set to S)
image

**Comment by ordovice** [comment]
You can help me out a lot.  Can you join the Batocera Nation discord and join me in the switch channel?  If you can connect both controllers with the base code and then enable controller debug and send me the es_launch_stdout.log I might be able to finally figure out what causes the reversed IDs

**Comment by ordovice** [comment]
To enable controller debug mode, create a text file called debugcontrollers.txt which just has a value of 1 in share\system\switch\configgen That will return data in the es_launch_stdout.log that might finally help me crack this bug.

**Comment by drizzt** [comment]
I wrote to you on discord (I'm still drizzt)... btw, should I use the beta batocera version or may I use 37?

**Pull request closed without merging**
