### PR TITLE
batocera-switch-updater patch3

### PR DESCRIPTION
**Pull request by uureel**
running the updater will now also: 
1. generate shortcuts for the emulators in F1-Applications menu
2. generate launchers for said shortcuts (for passing longer commands with env vars)
3. prepare a startup script inside /extra/ 
4. add nr3 to custom.sh so that f1 emulators are there upon reboot w/o overlay - also a way to resolve any/all batocera-switch dependencies @reboot

+ rename libthai for consistency
+ add switch.png icon to /extra/ for *.desktop F1-apps launchers
+ update to /extra/batocera-switch-updater.sh

### CODE REVIEW

**Comment by ordovice** [comment]
By changing libthai, you break the yuzuea  launcher.

**Comment by ordovice** [comment]
Additionally, why the version force in the yuzu URL?

**Comment by uureel** [comment]
> Additionally, why the version force in the yuzu URL?

yes my bad, pasted the line straight from testing link resolver, fixed

---
> Additionally, I do not want to force updates and changes upon users at reboot, so custom.sh must remain optional and not forced upon the users

it's just autostart, not so much updates per se. 
the purpose is to be able to fill any/all dependencies w/o using overlay, & add emu launchers to /usr/share/applications (i've seen people reporting issues with that and at some point during bato-betatesting i couldn't get them to show up any other way), i'm testing f1 launchers @ b36dev, works great.
additionally, due to ports updater now working live, any and all such solutions can get pulled/cleared at any time. 

---
> By changing libthai, you break the yuzuea launcher.

alright it's cosmetic not functional, nonissue

**Comment by uureel** [comment]
i've checked again and indeed it seems that ~/.local/share/applications is broken or turned off in b36 (or b35+) so the only way to get emus into F1 /usr/share/applications, so it is either using overlay, or custom.sh

overlay is something i definitely would avoid since 
1) if a user already made some changes it might need increased&/or unknown size 
2) it accumulates, so rolling it back removes all the stuff a user might've done for obvious reasons but this is also terrible

putting emus into F1 is however something i would definitely do for many reasons: 
1) general ease of use
2) some/new/adv options not pulled into ES
3) some games require/offer dlcs/mods etc

seems to me that custom.sh is the way to go, it's also only one line there that is easy to remove by the user, or clear using the updater itself, and if the user removes batocera-switch and leaves custom.sh, nothing bad will happen anyway

**Pull request merged**
